language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t tomboland/docker-dovecot-server .
  - docker run -d --name dovecot-server tomboland/docker-dovecot-server

script:
  - docker ps | grep -q dovecot-server
